language: java
before_script:
  - echo 'America/Sao_Paulo' | sudo tee /etc/timezone

jdk:
  - oraclejdk8

notifications:
    email:
        recipients:
            - diego+travisinterpretadorcodigobarras@devmonsters.com
        on_success: change
        on_failure: always